# fly.toml app configuration file generated for juancmandev-website on 2024-02-27T14:11:39-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'juancmandev-website'
primary_region = 'gdl'

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
