import Header from '@/components/Header';
import '@/styles/globals.css';
import '@fontsource/roboto';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <body className='w-screen h-screen text-white1 bg-dark2 overflow-hidden'>
        <Header />
        <main className='main overflow-auto'>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
